goshen:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: goshen-analytics
      dataset: analytics
      location: US
      threads: 4
      timeout_seconds: 300